name: Sync labels
on:
  schedule:
    # Runs at 12am IST
    - cron: '12 12 12 12 *'
  workflow_dispatch:

permissions:
  issues: write

jobs:
  labels:
    runs-on: ubuntu-latest

    steps:
      - uses: EndBug/label-sync@v2
        with:
          # If you want to use a config file, you can put its path or URL here, multiple files are also allowed (more info in the paragraphs below)
          config-file: 'https://raw.githubusercontent.com/Sleepyico/.github/master/.github/labels.yml'

          # If you want to delete any additional label, set this to true
          delete-other-labels: true

          # You can change the token used to change the labels, this is the default one
          token: ${{ secrets.GITHUB_TOKEN }}
